version: '3'
services: 
  django-services:
    image: "django-image:1.00"
    container_name: "django-container"
    tty: true
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      - .:/usr/django
    # env_file: my_env_file.env
